# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='clients', to='products.Product'),
        ),
        migrations.AddField(
            model_name='client',
            name='testimonials',
            field=models.ManyToManyField(blank=True, related_name='clients', to='clients.Testimonial'),
        ),
    ]
