# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='social',
        ),
        migrations.AddField(
            model_name='employee',
            name='social',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='company.Social'),
        ),
    ]
