# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicegroup',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_groups', to='photologue.Photo'),
        ),
        migrations.AlterField(
            model_name='servicegroup',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='groups', to='services.Service'),
        ),
    ]
